### PR TITLE
Upgrade to Swift 3.0 and RealmSwift 2.

### PR DESCRIPTION
**Pull request by johnantoni**
Upgraded to Swift 3 and RealmSwift 2.1.2.

Let me know what you think?

### CODE REVIEW

**Comment by hossamghareeb** [comment]
Hey @johnantoni , thanks a lot for the update and I think its really helpful. Will check and let you know.

**Comment by hossamghareeb** [comment]
Hey @johnantoni, I have checked your changes and all seems good except this part of code. I don't know why its added:

    // FIXME: comparison operators with optionals were removed from the Swift Standard Libary.
    // Consider refactoring the code to use the non-optional operators.
    fileprivate func < <T : Comparable>(lhs: T?, rhs: T?) -> Bool {
      switch (lhs, rhs) {
      case let (l?, r?):
        return l < r
      case (nil, _?):
        return true
      default:
        return false
      }
    }

    // FIXME: comparison operators with optionals were removed from the Swift Standard Libary.
    // Consider refactoring the code to use the non-optional operators.
    fileprivate func > <T : Comparable>(lhs: T?, rhs: T?) -> Bool {
      switch (lhs, rhs) {
      case let (l?, r?):
        return l > r
      default:
        return rhs < lhs
      }
    }

**Comment by johnantoni** [comment]
agree, @hossamghareeb that was part of the original code which I kept for consistency but I'm pretty certain it can be removed. no idea why it's in there.

**Comment by hossamghareeb** [comment]
No problem @johnantoni 👍 , I think its better if you removed it as adding them doesn't make any sense.

**Comment by johnantoni** [comment]
Ok removed, build working fine. let me know what you think @hossamghareeb

**Pull request merged**
